#+TITLE: Amazon Behavior Questions
#+AUTHOR: Dan Tran
#+DATE: Tue Aug  4 11:34:11 2020
#+STARTUP: showall
#+OPTIONS: ^:nil num:nil
#+SETUPFILE: ~/Documents/org/img/theme-notes.setup

* Popular questions with STAR template
** Tell me about a time when you were not able to meet a time commitment. What prevented you from meeting it? What was the outcome and what did you learn from it?
Sample answer: https://youtu.be/CQG4Ui0oAmk
- Situation: 
- Task:
- Action:
- Result:
** Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?
- Situation: 
- Task:
- Action:
- Result:
** Give me an example of a time when you set a goal and were able to meet or achieve it
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time you had to quickly adjust your work priorities to meet changing demands.
Sample answer: https://youtu.be/ys7fLcH5gpg
- Situation: 
- Task:
- Action:
- Result:
** Tell me an example when you push back to HQ or challenged a decision
- Situation: 
- Task:
- Action:
- Result:
** Tell me about the toughest decision you've had to make in the past six months
- Situation:
- Task:
- Action:
- Result:
** Tell me about a decision that you regret.
Sample answer: https://youtu.be/3NExTeMnobU
- Situation:
- Task:
- Action:
- Result:
** What did you do when you needed to motivate a group of individuals?
- Situation:
- Task:
- Action:
- Result:
** Tell me about a time you stepped up into a leadership role
Sample answer: https://youtu.be/Tg6BVRTsuic
- Situation: 
- Task:
- Action:
- Result:
** Do you collaborate well?
Sample answer: https://youtu.be/UJXkaide9bU
- Situation: 
- Task:
- Action:
- Result:
** Describe a situation when you negotiated with others in your organization to reach agreement.
- Situation:
- Task:
- Action: 
- Result:
** We've all had to work with people that don't like us. How do you deal with someone that doesn't like you?
Sample answer: https://youtu.be/ZsxkoZdyEcw
- Situation:
- Task:
- Action:
- Result:
** We all make mistakes we wish we could take back. Tell me about a time you wish you’d handled a situation differently with a colleague.
- Situation: 
- Task:
- Action:
- Result:
** The last time you had to apologize to someone
- Situation: 
- Task:
- Action:
- Result:
** Give me an example of a time you faced a conflict while working on a team. How did you handle that?
Sample answer: https://youtu.be/Zz8iQ852YMs
- Situation:
- Task:
- Action:
- Result: 
** Tell me about a time when you received negative feedback from your manager. How did you respond?
Sample answer: https://youtu.be/Zz8iQ852YMs
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time when you missed an obvious solution to a problem
- Situation:
- Task:
- Action:
- Result:
** A time when you faced a problem that had multiple possible solutions
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time when you came up with a new approach to a problem.
Sample answer: https://youtu.be/2XxCUain1IU
- Situation: 
- Task:
- Action:
- Result:
** Describe a time when you anticipated potential problems and developed preventive measures.
- Situation: 
- Task:
- Action:
- Result:
** Describe a situation in which you found a creative way to overcome an obstacle.
- Situation: 
- Task:
- Action:
- Result:
** How have you leveraged data to develop a strategy?
Sample answer: https://youtu.be/oRGKHTiM29E
- Situation: 
- Task:
- Action:
- Result:
** Tell me a time when you were 75% through a project, & you had to pivot strategy
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time when you had to choose between technologies for a project
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time you had to deal with ambiguity
- Situation: 
- Task:
- Action:
- Result:
** What’s the most innovative new idea that you have implemented?
Sample answer: https://youtu.be/774ovkE2y5I
- Situation: 
- Task:
- Action:
- Result:
** Describe a time when you sacrificed short term goals for long term success
- Situation: 
- Task:
- Action:
- Result:
** Provide an example of when you personally demonstrate ownership.
Sample answer: https://youtu.be/Rn3EjvukTkI
- Situation: 
- Task:
- Action:
- Result:

** What's your greatest strength
Sample answer: https://youtu.be/q8fK73QjmbA
- Situation: 
- Task:
- Action:
- Result:
** Biggest weakness
Sample answer: https://youtu.be/q8fK73QjmbA
- Situation: 
- Task:
- Action:
- Result:
** We all deal with difficult customers from time to time. Tell me about a challenging client-facing situation and how you handled it.
- Situation:
- Task:
- Action:
- Result:
** How do you show customer obsession?
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time you recovered from a difficult situation
- Situation: 
- Task:
- Action:
- Result:
** Tell me about a time you failed and what you learned from it
Sample answer: https://youtu.be/eaUUeFoB9CQ
- Situation:
- Task:
- Action:
- Result:
** Why Amazon
Sample answer: https://youtu.be/H_KGM0i9jkA
* General tips
- Shouldn't use “we” instead of “I”
- Practice and rehearse often
- Be specific in terms of quantifying results: for example, after completion the project, the latency reduce 50% and the service is able to handle 2x traffic
- Be positive: especially in question of failure, what is most important is what you learn from past mistakes.
- Study 14 leadership principles. For engineer role, you can skip 2 principles: hire and develop the best, frugality.
* Resources
- Algo Expert: https://www.algoexpert.io/behavioral-interviews
- Dan Croitor's Youtube channel: https://www.youtube.com/channel/UCw0uQHve23oMWgQcTTpgQsQ
